version: '2'

volumes:
  postgres_data: {}

services:

  backup-scheduler:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    restart: unless-stopped
    container_name: backup-scheduler
    privileged: true
    network_mode: "host"
    env_file:
      - docker-compose.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/postgres/backups:/postgres_backups
    command: ["node", "lib/backup-scheduler/backup-scheduler.js"]

  pbx-interface:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: pbx-interface
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    env_file:
      - docker-compose.env
    command: ["node", "lib/pbx-interface/pbx-interface.js"]
    depends_on:
      - tcs-postgres
      - tms-interface
      - database-interface

  tms-interface:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    command: ["node", "lib/tms-interface/tms-interface.js"]
    container_name: tms-interface
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    env_file:
      - docker-compose.env
   
  database-interface:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    env_file:
      - docker-compose.env
    command: ["node", "lib/database-interface/database-interface.js"]
    container_name: database-interface
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    depends_on: 
      - tcs-postgres
      - rabbitmq

  rabbitmq:
    image: letsxo/rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    privileged: true
    network_mode: "host"

  tcs-postgres:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: tcs-postgres
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    env_file:
      - docker-compose.env    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/postgres/backup_xlogs:/postgres_backup_xlogs
    entrypoint: /docker-entrypoint.sh
    command: ["postgres"]
    depends_on:
      - backup-scheduler

  tcs-image:
    build: 
      context: .
      dockerfile: ./src/tcs-image/Dockerfile
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: tcs-image

  tms-simulator:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: tms-simulator
    env_file:
      - docker-compose.env
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    command: ["node", "lib/tms-simulator/tms-simulator.js"]

  mangle:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    env_file:
      - docker-compose.env
    command: ["node", "lib/mangle/mangle.js"]
    container_name: mangle
    privileged: false
    volumes:
      - /home/smdr-data:/smdr-data

  pbx-simulator:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    env_file:
      - docker-compose.env
    command: ["node", "lib/pbx-simulator/pbx-simulator.js"]
    container_name: pbx-simulator
    privileged: false
    network_mode: "host"
    volumes:
      - /home/smdr-data:/smdr-data
