version: '2'
services:
  tcs:
    build:
      context: .
      dockerfile: ./dockerfiles/tcs
    environment:
      - DOCKER_MACHINE_IP=192.168.99.100
      - TMS_ACTIVE=0 # 1 if active, 0 if not active
      - STARTUP_DELAY=10000
    ports:
      - "3456:3456"
    links:
      - rabbitmq
      - postgres
      - tms-interface
      - database-interface
    volumes:
      - ./lib:/app
  tms-interface:
    build:
      context: .
      dockerfile: ./dockerfiles/tms-interface
    environment:
      - DOCKER_MACHINE_IP=192.168.99.100
      - TMS_PORT=6543
      - STARTUP_DELAY=10000
    links:
      - rabbitmq
    volumes:
      - ./lib:/app
  database-interface:
    build:
      context: .
      dockerfile: ./dockerfiles/database-interface
    environment:
      - DOCKER_MACHINE_IP=192.168.99.100
      - STARTUP_DELAY=10000
    links:
      - rabbitmq
      - postgres
  rabbitmq:
    image: letsxo/rabbitmq:latest
    ports:
      - "4369:4369"
      - "5671:5671"
      - "25672:25672"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
  telephony-simulator:
    build:
      context: .
      dockerfile: ./dockerfiles/telephony-simulator
    environment:
      - DOCKER_MACHINE_IP=192.168.99.100
      - TCS_PORT=3456
  tms-simulator:
    build:
      context: .
      dockerfile: ./dockerfiles/tms-simulator
    environment:
      - TMS_PORT=6543
    ports:
      - "6543:6543"
