tcs:
  build: .
  ports:
    - "3456:3456"
  links:
    - rabbitmq
    - postgres
  environment:
    - AMPQ_ADDRESS=amqp://rabbitmq:5672
    - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432
  volumes:
    - ./lib:/app
rabbitmq:
  image: rabbitmq
  ports:
    - 5672
postgres:
  image: postgres:latest
  ports:
    - 5432
