version: '2'
services:
  tcs:
    build:
      context: .
      dockerfile: ./dockerfiles/telephony-capture-service
    env_file:
      - docker-compose.env
    ports:
      - "3456:3456"
    links:
      - rabbitmq
      - postgres
      - tms-interface
      - database-interface
    volumes:
      - ./lib:/service/lib
  tms-interface:
    build:
      context: .
      dockerfile: ./dockerfiles/tms-interface
    env_file:
      - docker-compose.env
    links:
      - rabbitmq
    volumes:
      - ./lib:/service/lib
  database-interface:
    build:
      context: .
      dockerfile: ./dockerfiles/database-interface
    env_file:
      - docker-compose.env
    links:
      - rabbitmq
      - postgres
    volumes:
      - ./lib:/service/lib  
  rabbitmq:
    image: letsxo/rabbitmq:latest
    ports:
      - "4369:4369"
      - "5671:5671"
      - "25672:25672"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
  telephony-simulator:
    build:
      context: .
      dockerfile: ./dockerfiles/telephony-simulator
    env_file:
      - docker-compose.env
    volumes:
      - ./lib:/service/lib  
  tms-simulator:
    build:
      context: .
      dockerfile: ./dockerfiles/tms-simulator
    env_file:
      - docker-compose.env
    ports:
      - "6543:6543"
    volumes:
      - ./lib:/service/lib  
  mangle:
    build:
      context: .
      dockerfile: ./dockerfiles/mangle
    env_file:
      - docker-compose.env
    volumes:
      - /Users/Rod/smdr-data:/smdr-data
      - ./lib:/service/lib  
