version: '2'

volumes:
  postgres1_data: {}
  postgres2_data: {}
  postgres1_backup_xlogs: {}
  postgres2_backup_xlogs: {}

services:

  backup-scheduler:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    restart: unless-stopped
    container_name: backup-scheduler
    privileged: true
    network_mode: "host"
    environment:
      - BACKUP_PURGE_PERIOD_UNITS
      - BACKUP_PURGE_PERIOD_LIMIT
      - BACKUP_SCHEDULE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/postgres/backups:/postgres_backups
    command: ["node", "lib/backup-scheduler/backup-scheduler.js"]

  barman:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    restart: unless-stopped
    container_name: barman
    privileged: true
    network_mode: "host"
    volumes:
      - postgres1_data:/pg1_data
      - postgres2_data:/pg2_data
      - ~/barman_home:/var/lib/barman
    command: ["node", "./lib/share/forever.js"]

  database-interface:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: database-interface
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    depends_on: 
      - barman
      - rabbitmq
      - postgres1
      - postgres2
    environment:
      - POSTGRES_PASSWORD
    command: ["node", "lib/database-interface/database-interface.js"]
  
  mangle:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: mangle
    privileged: false
    volumes:
      - /home/smdr-data:/smdr-data
    command: ["node", "lib/mangle/mangle.js"]

  pbx-interface:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: pbx-interface
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - TCS_PORT=3456
      - TMS_ACTIVE=1    
    depends_on:
      - tms-interface
      - database-interface
    command: ["node", "lib/pbx-interface/pbx-interface.js"]

  pbx-simulator:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: pbx-simulator
    privileged: false
    network_mode: "host"
    volumes:
      - /home/smdr-data:/smdr-data
    environment:
      - PBX_SIMULATOR_SOURCE_DIRECTORY
      - TCS_PORT
    command: ["node", "lib/pbx-simulator/pbx-simulator.js"]

  postgres1:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: postgres1
    restart: unless-stopped
    privileged: true
    network_mode: "host"  
    volumes:
      - postgres1_data:/var/lib/postgresql/data
      - postgres1_backup_xlogs:/postgres_backup_xlogs
    entrypoint: /docker-entrypoint.sh
    environment:
      - POSTGRES_PASSWORD
    command: ["postgres"]

  postgres2:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: postgres2
    restart: unless-stopped
    privileged: true
    network_mode: "host"  
    volumes:
      - postgres2_data:/var/lib/postgresql/data
      - postgres2_backup_xlogs:/postgres_backup_xlogs
    entrypoint: /docker-entrypoint.sh
    environment:
      - POSTGRES_PASSWORD
    command: ["node", "./lib/share/forever.js"]

  rabbitmq:
    image: letsxo/rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    privileged: true
    network_mode: "host"

  tcs-image:
    build: 
      context: .
      dockerfile: ./src/tcs-image/Dockerfile
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: tcs-image

  tms-interface:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: tms-interface
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - TMS_HOST
      - TMS_PORT
    command: ["node", "lib/tms-interface/tms-interface.js"]
   
  tms-simulator:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: tms-simulator
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - TMS_PORT
    command: ["node", "lib/tms-simulator/tms-simulator.js"]
