version: '2'

volumes:
  data: {}

services:

  backup-scheduler:
    build:
      context: .
      dockerfile: ./src/backup-scheduler/Dockerfile
    image: backup-scheduler
    env_file:
      - docker-compose.env
    links:
      - postgres
    volumes:
      - /Users/Rod/postgres_backups:/postgres_backups
      - ./lib:/service/lib
  tcs:
    build:
      context: .
      dockerfile: ./src/telephony-capture-service/Dockerfile
    image: telephony-capture-service
    env_file:
      - docker-compose.env
    ports:
      - "3456:3456"
    links:
      - rabbitmq
      - tms-interface
      - database-interface
    volumes:
      - ./lib:/service/lib
  tms-interface:
    build:
      context: .
      dockerfile: ./src/tms-interface/Dockerfile
    image: tms-interface
    env_file:
      - docker-compose.env
    links:
      - rabbitmq
    volumes:
      - ./lib:/service/lib
  database-interface:
    build:
      context: .
      dockerfile: ./src/database-interface/Dockerfile
    image: database-interface
    env_file:
      - docker-compose.env
    links:
      - rabbitmq
      - postgres
    volumes:
      - ./lib:/service/lib  
  rabbitmq:
    image: letsxo/rabbitmq:latest
    ports:
      - "4369:4369"
      - "5671:5671"
      - "25672:25672"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
  postgres:
    build: 
      context: .
      dockerfile: ./src/postgres/Dockerfile
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
      - ../postgres_wal_directory:/postgres_wal_directory
  telephony-simulator:
    build:
      context: .
      dockerfile: ./src/telephony-simulator/Dockerfile
    image: telephony-simulator
    env_file:
      - docker-compose.env
    volumes:
      - ./lib:/service/lib
  tms-simulator:
    build:
      context: .
      dockerfile: ./src/tms-simulator/Dockerfile
    image: tms-simulator
    env_file:
      - docker-compose.env
    ports:
      - "6543:6543"
    volumes:
      - ./lib:/service/lib  
  mangle:
    build:
      context: .
      dockerfile: ./src/mangle/Dockerfile
    image: mangle
    env_file:
      - docker-compose.env
    volumes:
      - /Users/Rod/smdr-data:/smdr-data
      - ./lib:/service/lib  
