version: '2'

services:

  database-interface:
    container_name: ${TCSENV}-database-interface
    env_file: ./env_PROD/.env
    volumes:
      - /etc/localtime:/etc/localtime

  mangle:
    container_name: ${TCSENV}-mangle
    env_file: ./env_PROD/.env
    volumes:
      - /etc/localtime:/etc/localtime
      - $SMDR_DATA_PROD:/smdr-data

  pbx-interface:
    container_name: ${TCSENV}-pbx-interface
    env_file: ./env_PROD/.env
    depends_on:
      - tms-interface
      - database-interface
    volumes:
      - $SMDR_DATA_PROD:/smdr-data
      - /etc/localtime:/etc/localtime
 
  pbx-simulator:
    container_name: ${TCSENV}-pbx-simulator
    env_file: ./env_PROD/.env
    volumes:
      - /etc/localtime:/etc/localtime
      - $SMDR_DATA_PROD:/smdr-data
 
  tms-interface:
    container_name: ${TCSENV}-tms-interface
    env_file: ./env_PROD/.env
    volumes:
      - /etc/localtime:/etc/localtime

  tms-simulator:
    container_name: ${TCSENV}-tms-simulator
    env_file: ./env_PROD/.env
    volumes:
      - /etc/localtime:/etc/localtime
