version: '2'

services:

  database-interface:
    container_name: QA-database-interface
    environment:
      - DATABASE=qa
      - DB_QUEUE=QA_DB_QUEUE

  mangle:
    container_name: QA-mangle

  pbx-interface:
    container_name: QA-pbx-interface
    environment:
      - TCS_PORT=3458
      - TMS_ACTIVE=1 
      - DB_QUEUE=QA_DB_QUEUE
      - TMS_QUEUE=QA_TMS_QUEUE
    volumes:
      - ./lib:/app/lib
 
  pbx-simulator:
    environment:
      - PBX_SIMULATOR_SOURCE_DIRECTORY=/smdr-data
    container_name: QA-pbx-simulator
 
  tms-interface:
    container_name: QA-tms-interface
    environment:
      - TMS_QUEUE=QA_TMS_QUEUE
      - TMS_PORT=6545
    volumes:
      - ./lib:/app/lib

  tms-simulator:
    container_name: QA-tms-simulator
    environment:
      - TMS_PORT=6545

  tcs-qa:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    container_name: tcs-qa
    privileged: false
    network_mode: "host"
    environment:
      - PBX_SIMULATOR_SOURCE_DIRECTORY
      - TCS_PORT=3458
      - TMS_PORT=6545
    entrypoint: ["node", "./lib/jenkins/test-rabbit-interruption-part2.js"]
    volumes:
      - ./lib:/app/lib
