version: '2'

services:

  database-interface:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD
    command: ["./lib/database-interface/database-interface.js"]
  
  mangle:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    privileged: false
    volumes:
      - /home/smdr-data:/smdr-data
    command: ["./lib/mangle/mangle.js"]

  pbx-interface:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - TCS_PORT=3456
      - TMS_ACTIVE=1    
    depends_on:
      - tms-interface
      - database-interface
    entrypoint: ["./lib/pbx-interface/pbx-interface.js"]

  pbx-simulator:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    privileged: false
    network_mode: "host"
    volumes:
      - ./sample-data/smdr-data:/smdr-data
    entrypoint: ["./lib/pbx-simulator/pbx-simulator.js"]

  tms-interface:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - TMS_HOST
      - TMS_PORT
    entrypoint: ["./lib/tms-interface/tms-interface.js"]
   
  tms-simulator:
    image: ccbcadmin/tcs-image${TCS_VERSION}
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    environment:
      - TMS_PORT
    entrypoint: ["./lib/tms-simulator/tms-simulator.js"]

