version: '2'

services:

  database-interface:
    container_name: DEV-database-interface
    env_file: .env_dev
    volumes:
      - ./lib:/app/lib

  integrate:
    env_file: .env_dev
    volumes:
      - ./lib:/app/lib

  mangle:
    container_name: DEV-mangle
    env_file: .env_dev
    volumes:
      - ./lib:/app/lib

  pbx-interface:
    container_name: DEV-pbx-interface
    env_file: .env_dev
    depends_on:
      - tms-interface
      - database-interface
      - tms-simulator
    volumes:
      - ./lib:/app/lib

  pbx-simulator:
    container_name: DEV-pbx-simulator
    env_file: .env_dev
    volumes:
      - ./lib:/app/lib

  tms-interface:
    container_name: DEV-tms-interface
    env_file: .env_dev 
    volumes:
      - ./lib:/app/lib

  tms-simulator:
    container_name: DEV-tms-simulator
    env_file: .env_dev
    volumes:
      - ./lib:/app/lib
