version: '2'

services:

  database-interface:
    container_name: PROD-database-interface
    environment:

  mangle:
    container_name: PROD-mangle

  pbx-interface:
    container_name: PROD-pbx-interface
    env_file: .prod_env
    depends_on:
      - tms-interface
      - database-interface
      - pbx-simulator
 
  pbx-simulator:
    container_name: PROD-pbx-simulator
    env_file: .prod_env
 
  tms-interface:
    container_name: PROD-tms-interface
    env_file: .prod_env

  tms-simulator:
    container_name: PROD-tms-simulator
    env_file: .prod_env
